[[redirects]]
  from = "/"
  to = "/block"
  force = true

[[redirects]]
  from = "/login"
  to = "/block"
  force = true

[[redirects]]
  from = "/signup"
  to = "/block"
  force = true

[[redirects]]
  from = "/copilot"
  to = "/block"
  force = true

[[edge_functions]]
  path = "/*"
  function = "proxy"